name: flutter_blog_clean_arch_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  dotted_border: ^2.1.0

  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3

  # Serialization
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Network
  http: ^1.2.1
  supabase_flutter: ^2.3.4
  internet_connection_checker_plus: ^2.3.0

  # Security
  flutter_dotenv: ^5.1.0

  # Localization
  easy_localization: ^3.0.5

  # Utils
  image_picker: ^1.0.7
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/env/.env
    - assets/env/.dev.env
    - assets/language/
